eureka:
  client:
    serviceUrl:
      defaultZone: http://58.87.96.195:8761/eureka/
server:
  port: 8760

feign:
  url: http://58.87.96.195:8762
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
